db:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'y4cb'
  password: 'sKJt9KGxCSqRAWeC'
  database: 'tiktok'
  autoLoadEntities: true
  synchronize: false
  logger: 'simple-console'
  logging: true
  entities: ['dist/**/*.entity{.ts,.js}']
  keepConnectionAlive: true

auth:
  smsCodeLifetime: '1 hours'
  jwt:
    secret: 'B2bsvdqPwJ2HzE7VAVcm4YBdpXhaJ4VQXCyMz7Rc'
    tokenLifetime:
      access: '2 hours' # https://github.com/vercel/ms
      refresh: '4 weeks'
