db:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'ti89o1'
  password: '69kPMcAkHu7fD'
  database: 'tiktok_test'
  autoLoadEntities: true
  synchronize: false
  logging: false
  entities: ['dist/**/*.entity{.ts,.js}']
  keepConnectionAlive: true

auth:
  smsCodeLifetime: '1 hours'
  jwt:
    secret: 'B2bsvdqPwJ2HzE7VAVcm4YBdpXhaJ4VQXCyMz7Rc'
    tokenLifetime:
      access: '2 hours'
      refresh: '4 weeks'

dirs:
  src: 'not defined'

pagination:
  videos:
    limit:
      default: 20
      max: 50
